name: secure_evoting_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  flutter_secure_storage: ^4.2.1
  hexcolor: ^3.0.1
  get: ^4.6.6
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  image_picker: ^1.0.8
  permission_handler: ^11.3.1
  image: ^4.1.7
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  getwidget: ^4.0.0
  firebase_storage: ^11.6.9
  motion_tab_bar_v2: ^0.3.0
  cached_network_image: ^3.3.1
  intl: ^0.18.0
  path: ^1.8.3
  flutter_easyloading: ^3.0.5
  firebase_core: ^2.27.0
  google_fonts: 5.1.0
  http: ^1.2.0
  bcrypt: ^1.1.3
  qr_code_scanner: ^1.0.1
  otp_text_field: ^1.1.3
  carousel_slider: ^4.2.1
  face_camera: ^0.1.0
  path_provider: ^2.1.3
  file_picker: ^8.0.0+1
  aes_crypt_null_safe: ^2.0.2
  flutter_chat_bubble: ^2.0.2
  encrypt: ^5.0.3
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/CustomIcon.ttf
        
    - family: Blinker
      fonts:
        - asset: assets/fonts/Blinker-ExtraBold.ttf

